export default {
   async linhabonus(idjson: string) {
      const jsons: any = {
         [1]: {
            [0]: {
               it: false,
               wp: { "2": [0, 3, 6], "4": [0, 4, 8], "5": [2, 4, 6] },
               cwc: 1,
               lw: { "2": 1.8, "4": 3.0, "5": 1.8 },
               orl: [0, 5, 6, 0, 0, 5, 6, 7, 5],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 10, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "2": 3.0, "4": 5.0, "5": 3.0 },
               rl: [0, 5, 6, 0, 0, 5, 6, 7, 5],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [2, 2, 7, 5, 5, 3, 0, 6, 6],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [2, 2, 7, 5, 5, 3, 0, 6, 6],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [5, 7, 4, 7, 7, 7, 5, 6, 6],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [5, 7, 4, 7, 7, 7, 5, 6, 6],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [5, 3, 3, 0, 0, 4, 7, 7, 6],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 2, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [5, 3, 3, 0, 0, 4, 7, 7, 6],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [6, 2, 2, 2, 5, 0, 6, 6, 6],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: null,
               rl: [6, 2, 2, 2, 5, 0, 6, 6, 6],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: { "1": [1, 4, 7], "2": [0, 3, 6], "4": [0, 4, 8], "5": [2, 4, 6] },
               cwc: 1,
               lw: { "1": 1.8, "2": 1.8, "4": 1.8, "5": 1.8 },
               orl: [0, 0, 0, 6, 6, 5, 6, 6, 6],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "1": 3.0, "2": 3.0, "4": 3.0, "5": 3.0 },
               rl: [0, 0, 0, 6, 6, 5, 6, 6, 6],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: { "5": [2, 4, 6] },
               cwc: 1,
               lw: { "5": 6.0 },
               orl: [3, 3, 4, 7, 4, 3, 4, 4, 4],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 2, 10, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "5": 10.0 },
               rl: [3, 3, 4, 7, 4, 3, 4, 4, 4],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [6, 6, 5, 5, 5, 7, 2, 2, 5],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 2, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [6, 6, 5, 5, 5, 7, 2, 2, 5],
            },
         },
         [2]: {
            [0]: {
               it: false,
               wp: { "1": [1, 4, 7], "2": [0, 3, 6], "4": [0, 4, 8] },
               cwc: 1,
               lw: { "1": 1.8, "2": 1.8, "4": 1.8 },
               orl: [6, 6, 5, 6, 6, 7, 6, 6, 6],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 10, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "1": 3, "2": 3, "4": 3 },
               rl: [6, 6, 5, 6, 6, 7, 6, 6, 6],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [5, 2, 2, 4, 4, 5, 5, 3, 3],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [5, 2, 2, 4, 4, 5, 5, 3, 3],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [5, 2, 2, 6, 6, 5, 5, 5, 5],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [5, 2, 2, 6, 6, 5, 5, 5, 5],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [6, 6, 2, 5, 5, 6, 7, 7, 6],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 2, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [6, 6, 2, 5, 5, 6, 7, 7, 6],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [5, 6, 7, 3, 3, 4, 5, 7, 7],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: null,
               rl: [5, 6, 7, 3, 3, 4, 5, 7, 7],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: { "4": [0, 4, 8] },
               cwc: 1,
               lw: { "4": 1.2 },
               orl: [7, 6, 6, 5, 7, 7, 4, 7, 7],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "4": 2 },
               rl: [7, 6, 6, 5, 7, 7, 4, 7, 7],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: { "1": [1, 4, 7] },
               cwc: 1,
               lw: { "1": 3 },
               orl: [2, 5, 3, 4, 5, 7, 0, 5, 2],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 2, 10, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "1": 5 },
               rl: [2, 5, 3, 4, 5, 7, 0, 5, 2],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [4, 4, 3, 5, 4, 4, 6, 3, 3],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 10, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [4, 4, 3, 5, 4, 4, 6, 3, 3],
            },
         },
         [3]: {
            [0]: {
               it: false,
               wp: { "1": [1, 4, 7], "5": [2, 4, 6] },
               cwc: 1,
               lw: { "1": 1.2, "5": 1.2 },
               orl: [2, 0, 0, 3, 7, 7, 7, 7, 4],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 10, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "1": 2, "5": 2 },
               rl: [2, 0, 0, 3, 7, 7, 7, 7, 4],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [5, 6, 6, 7, 5, 5, 3, 7, 7],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [5, 6, 6, 7, 5, 5, 3, 7, 7],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [4, 7, 6, 6, 5, 0, 3, 7, 7],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [4, 7, 6, 6, 5, 0, 3, 7, 7],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [4, 4, 2, 5, 6, 6, 3, 4, 4],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 2, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [4, 4, 2, 5, 6, 6, 3, 4, 4],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [7, 7, 6, 5, 7, 7, 7, 5, 2],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: null,
               rl: [7, 7, 6, 5, 7, 7, 7, 5, 2],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: { "2": [0, 3, 6] },
               cwc: 1,
               lw: { "2": 1.8 },
               orl: [6, 6, 7, 6, 7, 2, 6, 5, 4],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "2": 3 },
               rl: [6, 6, 7, 6, 7, 2, 6, 5, 4],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: { "3": [2, 5, 8] },
               cwc: 1,
               lw: { "3": 6 },
               orl: [2, 0, 0, 5, 6, 4, 4, 3, 4],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "3": 10 },
               rl: [2, 0, 0, 5, 6, 4, 4, 3, 4],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [2, 5, 6, 7, 7, 6, 4, 7, 7],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 10, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [2, 5, 6, 7, 7, 6, 4, 7, 7],
            },
         },
         [4]: {
            [0]: {
               it: false,
               wp: { "2": [0, 3, 6] },
               cwc: 1,
               lw: { "2": 3 },
               orl: [5, 5, 5, 5, 6, 4, 5, 3, 3],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 10, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "2": 5 },
               rl: [5, 5, 5, 5, 6, 4, 5, 3, 3],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [4, 5, 5, 0, 5, 4, 7, 6, 5],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [4, 5, 5, 0, 5, 4, 7, 6, 5],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [7, 3, 3, 4, 4, 5, 3, 4, 4],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [7, 3, 3, 4, 4, 5, 3, 4, 4],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [3, 2, 5, 5, 5, 6, 2, 2, 2],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 2, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [3, 2, 5, 5, 5, 6, 2, 2, 2],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [2, 2, 2, 2, 2, 2, 6, 7, 4],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: null,
               rl: [2, 2, 2, 2, 2, 2, 6, 7, 4],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: { "3": [2, 5, 8] },
               cwc: 1,
               lw: { "3": 6 },
               orl: [6, 2, 4, 2, 4, 4, 2, 3, 4],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "2": 3 },
               rl: [6, 2, 4, 2, 4, 4, 2, 3, 4],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: { "2": [0, 3, 6], "5": [2, 4, 6] },
               cwc: 1,
               lw: { "2": 1.8, "5": 1.2 },
               orl: [6, 6, 7, 6, 7, 7, 0, 6, 4],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "2": 3, "5": 2 },
               rl: [6, 6, 7, 6, 7, 7, 0, 6, 4],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [2, 2, 2, 6, 6, 6, 5, 6, 0],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 10, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [2, 2, 2, 6, 6, 6, 5, 6, 0],
            },
         },
         [5]: {
            [0]: {
               it: false,
               wp: { "3": [2, 5, 8] },
               cwc: 1,
               lw: { "3": 6 },
               orl: [3, 6, 4, 5, 6, 4, 2, 2, 4],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 10, 10, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "3": 10 },
               rl: [3, 6, 4, 5, 6, 4, 2, 2, 4],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [5, 2, 5, 4, 5, 6, 7, 4, 4],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [5, 2, 5, 4, 5, 6, 7, 4, 4],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [2, 7, 7, 6, 6, 4, 2, 6, 3],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [2, 7, 7, 6, 6, 4, 2, 6, 3],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [7, 6, 5, 0, 4, 4, 5, 5, 7],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 2, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [7, 6, 5, 0, 4, 4, 5, 5, 7],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [5, 5, 3, 4, 4, 5, 2, 3, 4],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: null,
               rl: [5, 5, 3, 4, 4, 5, 2, 3, 4],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: { "2": [0, 3, 6], "4": [0, 4, 8] },
               cwc: 1,
               lw: { "2": 15, "4": 15 },
               orl: [3, 2, 4, 3, 3, 3, 3, 3, 3],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "2": 25, "4": 25 },
               rl: [3, 2, 4, 3, 3, 3, 3, 3, 3],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [2, 2, 3, 6, 4, 4, 4, 4, 4],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [2, 2, 3, 6, 4, 4, 4, 4, 4],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [0, 4, 4, 5, 5, 6, 3, 3, 7],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 10, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [0, 4, 4, 5, 5, 6, 3, 3, 7],
            },
         },
         [6]: {
            [0]: {
               it: false,
               wp: { "3": [2, 5, 8] },
               cwc: 1,
               lw: { "3": 15 },
               orl: [3, 3, 3, 4, 4, 3, 5, 7, 3],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 2, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "3": 25 },
               rl: [3, 3, 3, 4, 4, 3, 5, 7, 3],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [6, 2, 2, 5, 5, 7, 4, 4, 4],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [6, 2, 2, 5, 5, 7, 4, 4, 4],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: { "3": [2, 5, 8] },
               cwc: 0,
               lw: { "3": 1.8 },
               orl: [5, 7, 6, 7, 5, 6, 6, 6, 6],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "3": 3 },
               rl: [5, 7, 6, 7, 5, 6, 6, 6, 6],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: { "3": [2, 5, 8] },
               cwc: 0,
               lw: { "3": 1.2 },
               orl: [7, 7, 7, 5, 5, 7, 6, 5, 7],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 2, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "4": 2 },
               rl: [7, 7, 7, 5, 5, 7, 6, 5, 7],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [3, 4, 5, 3, 4, 5, 6, 3, 3],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: null,
               rl: [3, 4, 5, 3, 4, 5, 6, 3, 3],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: { "1": [1, 4, 7] },
               cwc: 1,
               lw: { "1": 3 },
               orl: [4, 5, 6, 6, 5, 3, 4, 0, 7],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "1": 5 },
               rl: [4, 5, 6, 6, 5, 3, 4, 0, 7],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [3, 6, 4, 4, 6, 2, 3, 3, 4],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [3, 6, 4, 4, 6, 2, 3, 3, 4],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [5, 5, 0, 5, 5, 5, 4, 7, 7],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 10, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [5, 5, 0, 5, 5, 5, 4, 7, 7],
            },
         },
         [7]: {
            [0]: {
               it: false,
               wp: { "2": [0, 3, 6], "4": [0, 4, 8] },
               cwc: 1,
               lw: { "2": 1.8, "4": 1.8 },
               orl: [6, 2, 2, 6, 6, 5, 6, 6, 6],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 2, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "2": 3, "4": 3 },
               rl: [6, 2, 2, 6, 6, 5, 6, 6, 6],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [6, 6, 5, 7, 5, 5, 6, 6, 6],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [6, 6, 5, 7, 5, 5, 6, 6, 6],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: { "3": [2, 5, 8] },
               cwc: 0,
               lw: { "3": 1.2 },
               orl: [6, 2, 7, 5, 5, 7, 4, 7, 7],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "3": 2 },
               rl: [6, 2, 7, 5, 5, 7, 4, 7, 7],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: { "4": [0, 4, 8] },
               cwc: 0,
               lw: { "4": 6 },
               orl: [4, 3, 2, 6, 4, 4, 7, 7, 4],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 2, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "4": 10 },
               rl: [4, 3, 2, 6, 4, 4, 7, 7, 4],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: { "1": [1, 4, 7], "5": [2, 4, 6] },
               cwc: 0,
               lw: { "1": 15, "5": 15 },
               orl: [5, 3, 3, 0, 0, 0, 3, 3, 7],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: { "1": 25, "5": 25 },
               rl: [5, 3, 3, 0, 0, 0, 3, 3, 7],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [2, 2, 2, 5, 3, 3, 5, 6, 7],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [2, 2, 2, 5, 3, 3, 5, 6, 7],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [3, 2, 5, 4, 6, 6, 2, 2, 2],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [3, 2, 5, 4, 6, 6, 2, 2, 2],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [5, 5, 6, 2, 2, 2, 2, 2, 2],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 10, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [5, 5, 6, 2, 2, 2, 2, 2, 2],
            },
         },
         [8]: {
            [0]: {
               it: false,
               wp: { "1": [1, 4, 7], "4": [0, 4, 8] },
               cwc: 1,
               lw: { "1": 1.8, "4": 1.8 },
               orl: [6, 6, 2, 6, 6, 7, 7, 0, 0],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 2, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "2": 3, "4": 3 },
               rl: [6, 6, 2, 6, 6, 7, 7, 0, 0],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [6, 6, 2, 6, 3, 4, 7, 4, 4],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [6, 6, 2, 6, 3, 4, 7, 4, 4],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [3, 3, 2, 5, 6, 6, 2, 2, 2],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [3, 3, 2, 5, 6, 6, 2, 2, 2],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [3, 2, 5, 6, 6, 6, 2, 2, 4],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 2, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [3, 2, 5, 6, 6, 6, 2, 2, 4],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [3, 4, 4, 6, 6, 5, 6, 6, 2],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: null,
               rl: [3, 4, 4, 6, 6, 5, 6, 6, 2],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [5, 5, 3, 6, 2, 5, 3, 4, 4],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [5, 5, 3, 6, 2, 5, 3, 4, 4],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [2, 2, 2, 2, 5, 5, 4, 0, 0],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [2, 2, 2, 2, 5, 5, 4, 0, 0],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [5, 4, 4, 6, 4, 6, 2, 2, 2],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 10, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [5, 4, 4, 6, 4, 6, 2, 2, 2],
            },
         },
         [9]: {
            [0]: {
               it: false,
               wp: { "1": [1, 4, 7], "4": [0, 4, 8] },
               cwc: 1,
               lw: { "1": 3, "4": 3 },
               orl: [5, 5, 2, 5, 5, 6, 3, 5, 5],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 2, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "1": 5, "4": 5 },
               rl: [5, 5, 2, 5, 5, 6, 3, 5, 5],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [2, 7, 3, 5, 7, 6, 3, 3, 7],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [2, 7, 3, 5, 7, 6, 3, 3, 7],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [3, 3, 6, 6, 7, 7, 6, 6, 6],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [3, 3, 6, 6, 7, 7, 6, 6, 6],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [3, 4, 5, 4, 5, 7, 2, 2, 2],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 2, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [3, 4, 5, 4, 5, 7, 2, 2, 2],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [2, 2, 2, 2, 7, 3, 3, 3, 7],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: null,
               rl: [2, 2, 2, 2, 7, 3, 3, 3, 7],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [3, 3, 3, 6, 4, 6, 2, 5, 5],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [3, 3, 3, 6, 4, 6, 2, 5, 5],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [6, 6, 6, 7, 7, 5, 7, 4, 4],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [6, 6, 6, 7, 7, 5, 7, 4, 4],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [3, 2, 4, 6, 6, 6, 2, 2, 2],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 10, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [3, 2, 4, 6, 6, 6, 2, 2, 2],
            },
         },
         [10]: {
            [0]: {
               it: false,
               wp: { "2": [0, 3, 6] },
               cwc: 1,
               lw: { "2": 1.2 },
               orl: [7, 3, 3, 7, 4, 0, 0, 5, 6],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 2, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "2": 2 },
               rl: [7, 3, 3, 7, 4, 0, 0, 5, 6],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [3, 4, 5, 4, 5, 7, 4, 2, 2],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [3, 4, 5, 4, 5, 7, 4, 2, 2],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [6, 3, 3, 6, 6, 6, 3, 3, 4],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [6, 3, 3, 6, 6, 6, 3, 3, 4],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [2, 2, 3, 2, 2, 6, 4, 4, 3],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 2, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [2, 2, 3, 2, 2, 6, 4, 4, 3],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [5, 3, 3, 7, 2, 4, 2, 2, 2],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: null,
               rl: [5, 3, 3, 7, 2, 4, 2, 2, 2],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [4, 5, 2, 4, 4, 5, 3, 2, 2],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [4, 5, 2, 4, 4, 5, 3, 2, 2],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [5, 2, 2, 4, 0, 6, 7, 7, 4],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [5, 2, 2, 4, 0, 6, 7, 7, 4],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [5, 5, 4, 6, 4, 6, 3, 3, 2],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 10, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [5, 5, 4, 6, 4, 6, 3, 3, 2],
            },
         },
         [11]: {
            [0]: {
               it: false,
               wp: { "3": [2, 5, 8] },
               cwc: 1,
               lw: { "3": 1.8 },
               orl: [6, 6, 6, 7, 7, 0, 6, 6, 6],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 2, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "3": 3 },
               rl: [6, 6, 6, 7, 7, 0, 6, 6, 6],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: { "2": [0, 3, 6], "4": [0, 4, 8] },
               cwc: 0,
               lw: { "2": 6, "4": 6 },
               orl: [4, 4, 2, 4, 0, 6, 4, 3, 4],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 2, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "2": 10, "4": 10 },
               rl: [4, 4, 2, 4, 0, 6, 4, 3, 4],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [3, 3, 2, 6, 7, 7, 7, 7, 6],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [3, 3, 2, 6, 7, 7, 7, 7, 6],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [2, 5, 5, 5, 5, 6, 2, 4, 3],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 10, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [2, 5, 5, 5, 5, 6, 2, 4, 3],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [7, 6, 6, 5, 5, 7, 3, 4, 4],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: null,
               rl: [7, 6, 6, 5, 5, 7, 3, 4, 4],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [4, 2, 3, 4, 6, 2, 3, 4, 4],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [4, 2, 3, 4, 6, 2, 3, 4, 4],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [4, 4, 5, 6, 5, 7, 7, 5, 4],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 10, 10, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [4, 4, 5, 6, 5, 7, 7, 5, 4],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [2, 5, 6, 5, 7, 6, 7, 7, 4],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 2, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [2, 5, 6, 5, 7, 6, 7, 7, 4],
            },
         },
         [12]: {
            [0]: {
               it: false,
               wp: { "3": [2, 5, 8], "5": [2, 4, 6] },
               cwc: 1,
               lw: { "3": 1.2, "5": 1.2 },
               orl: [6, 5, 7, 0, 7, 7, 7, 7, 7],
               fs: { s: 0, ts: 8, aw: 180.0 },
               mf: { mt: [10, 2, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "3": 2, "5": 2 },
               rl: [6, 5, 7, 0, 7, 7, 7, 7, 7],
               st: 2,
               nst: 1,
            },
            [1]: {
               it: false,
               wp: { "2": [0, 3, 6] },
               cwc: 0,
               lw: { "2": 1.8 },
               orl: [6, 5, 6, 6, 4, 7, 6, 7, 7],
               fs: { s: 1, ts: 8, aw: 100.8 },
               mf: { mt: [2, 2, 2, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: { "2": 3 },
               rl: [6, 5, 6, 6, 4, 7, 6, 7, 7],
               st: 2,
               nst: 2,
            },
            [2]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [2, 5, 3, 4, 5, 7, 3, 4, 4],
               fs: { s: 2, ts: 8, aw: 100.8 },
               mf: { mt: [5, 5, 5, 10], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [2, 5, 3, 4, 5, 7, 3, 4, 4],
               st: 2,
               nst: 2,
            },
            [3]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [4, 2, 3, 4, 5, 4, 3, 3, 2],
               fs: { s: 3, ts: 8, aw: 100.8 },
               mf: { mt: [10, 10, 5, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [4, 2, 3, 4, 5, 4, 3, 3, 2],
               st: 2,
               nst: 2,
            },
            [4]: {
               it: false,
               wp: null,
               cwc: 0,
               lw: null,
               orl: [0, 4, 4, 4, 5, 7, 5, 5, 4],
               fs: { s: 4, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2], ms: [true, true, true], mi: [0, 1, 2] },
               rwsp: null,
               rl: [0, 4, 4, 4, 5, 7, 5, 5, 4],
               st: 2,
               nst: 2,
            },
            [5]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [4, 3, 3, 2, 4, 6, 2, 2, 2],
               fs: { s: 5, ts: 8, aw: 100.8 },
               mf: { mt: [5, 2, 2, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [4, 3, 3, 2, 4, 6, 2, 2, 2],
               st: 2,
               nst: 2,
            },
            [6]: {
               it: false,
               wp: null,
               cwc: 1,
               lw: null,
               orl: [4, 7, 6, 2, 2, 7, 7, 6, 5],
               fs: { s: 6, ts: 8, aw: 72.0 },
               mf: { mt: [5, 10, 10, 5], ms: [false, true, true, false], mi: [1, 2] },
               rwsp: null,
               rl: [4, 7, 6, 2, 2, 7, 7, 6, 5],
               st: 2,
               nst: 2,
            },
            [7]: {
               it: true,
               wp: null,
               cwc: 0,
               orl: [5, 2, 2, 5, 6, 4, 4, 3, 3],
               fs: { s: 7, ts: 8, aw: 0.0 },
               mf: {
                  mt: [5, 5, 2, 5],
                  ms: [false, true, true, false],
                  mi: [1, 2],
               },
               rwsp: null,
               st: 1,
               nst: 2,
               rl: [5, 2, 2, 5, 6, 4, 4, 3, 3],
            },
         },
      }

      return jsons[idjson]
   },
}
