export default {
   async notcash(saldo: number, cs: number, ml: number) {
      return {
         dt: {
            si: {
               mrl: { "1": { wp: null, lw: null, tw: 0.0, rl: [1, 2, 3, 2, 3, 1, 2, 0, 3], orl: [2, 3, 0] }, "2": { wp: null, lw: null, tw: 0.0, rl: [2, 0, 1, 3, 1, 2, 3, 2, 1], orl: [0, 1, 2] } },
               gpt: 3,
               gwt: -1,
               fb: null,
               ctw: 0.0,
               pmt: null,
               cwc: 0,
               fstc: null,
               pcwc: 0,
               rwsp: null,
               hashr: null,
               ml: ml,
               cs: cs,
               rl: [-1, -1, -1],
               sid: "1773494329663424515",
               psid: "1773494329663424515",
               st: 1,
               nst: 1,
               pf: 1,
               aw: 0.0,
               wid: 0,
               wt: "C",
               wk: "0_C",
               wbn: null,
               wfg: null,
               blb: saldo,
               blab: saldo,
               bl: saldo,
               tb: 0.0,
               tbb: 0.0,
               tw: 0.0,
               np: 0.0,
               ocr: null,
               mr: null,
               ge: [1, 11],
            },
         },
         err: { cd: "3202", msg: "Not enough cash.", tid: "HDBQMG28" },
      }
   },
}
