export default {
   async notcash(saldo: number, cs: number, ml: number) {
      return {
         dt: {
            si: {
               wp: null,
               lw: null,
               ltw: 0.0,
               snww: null,
               fs: null,
               sc: 0,
               gwt: -1,
               fb: null,
               ctw: 0.0,
               pmt: null,
               cwc: 0,
               fstc: null,
               pcwc: 0,
               rwsp: null,
               hashr: null,
               ml: ml,
               cs: cs,
               rl: [2, 1, 5, 4, 3, 3, 0, 9, 7, 8, 8, 6, 7, 3, 6],
               sid: "1773366609377892866",
               psid: "1773366609377892866",
               st: 1,
               nst: 1,
               pf: 1,
               aw: 0.0,
               wid: 0,
               wt: "C",
               wk: "0_C",
               wbn: null,
               wfg: null,
               blb: saldo,
               blab: saldo,
               bl: saldo,
               tb: 0.0,
               tbb: 0.0,
               tw: 0.0,
               np: 0.0,
               ocr: null,
               mr: null,
               ge: [1, 11],
            },
         },
         err: { cd: "3202", msg: "Not enough cash.", tid: "TONNAO28" },
      }
   },
}
